# Generated by Django 4.1.5 on 2023-01-23 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='Adminregister',
        ),
    ]
